### ISSUE TITLE
Vokabeln verwalten

### ISSUE THREAD

**Issue by Julessh05** [NickRTR-Schule/Vokabeltrainer#1]
Als Lerner möchte ich Vokabeln als Text hinzufügen, anschauen, ändern und löschen, um diese später zu üben.

**Comment by NickRTR** [comment]
### Datenbank (Relationenschreibweise)

vokabel(<u>wort, uebersetzung</u>)
beziehung(<ins>*<u>vokabel</ins>*, *<u>kategorie</u>*</u>)
kategorie(<u>name</u>)

**Comment by NickRTR** [comment]
### UI

#### Screens

- Dashboard
  - Lernfortschritt / Statistiken
  - Kategorien anzeigen
    - Kategorien (letzte)
    - Kategorien (alle)
      - wenn leer: Kategorie erstellen

**Comment by Jules-sh** [comment]
> ### Datenbank
> #### Tabellen (Relationenschreibweise)
> vokabel(wort, uebersetzung, abbildung, aussprache, lautschrift, verwendungshinweise wiederholungen, anzahlrichtig) beziehung(_wort, uebersetzung_, _kategorie_) kategorie(name)
> 
> #### Benötigte SQL-Abfragen
> * Alle Vokabeln abfragen
> * Alle Vokabeln einer Kategorie abfragen
> * Lernfortschritt einer bestimmten Vokabel abfragen

Den Treiber zur Datenbank in das Projekt hinzufügen, da der Pfad zu den Treibern sonst bei allen gleich sein muss, da dieser ja im .classpath steht

**Comment by NickRTR** [comment]
Mach ich 👍

**Comment by Julessh05** [comment]
Closed with 1421b15
